# Generated by Django 4.1.2 on 2022-10-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_geeksmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
    ]
