# Generated by Django 4.1.2 on 2022-10-13 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_remove_geeksmodel_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
